[package]
name = "misaki-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10"
num2words = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
fancy-regex = "0.13"
